name: prokit_flutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.4.8
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.1.0

  # FIREBASE PACKAGES
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_crashlytics: ^2.1.1
  cloud_firestore: ^2.4.0

  # Common
  share: ^2.0.4
  url_launcher: ^6.0.3
  http: ^0.13.3
  html: ^0.15.0
  package_info: ^2.0.2

  # IMAGES
  cached_network_image: ^3.1.0
  image_picker: ^0.8.1+3
  file_picker: ^3.0.1
  photo_view: ^0.12.0
  card_swiper: ^1.0.2

  # AUTHENTICATION
  google_sign_in: ^5.0.4
  local_auth: ^1.1.6

  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  # MAP
  google_maps_flutter: ^2.0.6
  geolocator: ^7.3.1
  geocoding: ^2.0.0

  # WEB TOOLS
  webview_flutter: ^2.0.8

  # ADS
  google_mobile_ads: ^0.12.2

  # UI
  simple_animations: ^3.1.1
  flutter_svg: ^0.22.0
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: ^1.0.0
  flutter_colorpicker: ^0.4.0
  signature: ^4.1.1
  dots_indicator: ^2.0.0
  percent_indicator: ^3.0.1
  carousel_slider: ^4.0.0
  animations: ^2.0.1
  lottie: ^1.1.0
  liquid_swipe: ^2.1.0
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_reaction_button: ^1.0.8
  showcaseview: ^1.0.0
  fl_chart: 0.36.1
  syncfusion_flutter_charts: ^19.1.67

  # VIDEOS
  video_player: ^2.1.4

  # NOTIFICATION
  flutter_local_notifications: ^5.0.0+4
  onesignal_flutter: ^3.2.3

  #Dimond kit
  sleek_circular_slider: ^2.0.0
  sliding_up_panel: ^2.0.0+1

  otp_text_field: ^1.1.1

  # Cloud Storage #
  expandable_bottom_sheet: ^1.0.0+2
  multi_image_picker: ^4.8.00
  razorpay_flutter: ^1.2.7
  collection: ^1.15.0

  # PDF VIEWER #
  syncfusion_flutter_pdfviewer: ^19.2.55-beta

  # Generate QR Code #
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  #Temporary disabled due to lake of null safety
  #charts_flutter: ^0.11.0
  #geocoder: 0.2.1
  #geohash: ^0.2.1
  #snaplist: 0.1.8
  #lipsum: 1.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - fonts/
    - assets/
    - images/
    - images/app/icons/
    - images/app/
    - images/app/socialIcons/
    - images/widgets/
    - images/widgets/materialWidgets/
    - images/widgets/interactionModelWidgets/
    - images/widgets/cupertinoWidgets/
    - images/widgets/materialWidgets/mwAppStructureWidgets/
    - images/widgets/materialWidgets/mwDialogAlertPanelWidgets/
    - images/widgets/paintingAndEffectWidgets/
    - images/widgets/animationAndMotionWidgets/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/
    - images/widgets/materialWidgets/mwLayoutWidgtes/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/
    - images/widgets/materialWidgets/mwLayoutWidgtes/MWUserAccountDrawerHeaderWidget/
    - images/widgets/materialWidgets/mwLayoutWidgtes/MWListTile/
    - images/widgets/materialWidgets/mwAppStructureWidgets/BottomNavigation/
    - images/widgets/materialWidgets/mwAppStructureWidgets/TabBar/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/switch/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/Checkbox/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/cards/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/gridview/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/listView/
    - images/widgets/paintingAndEffectWidgets/opacity/
    - images/integrations/img/
    - images/integrations/icons/
    - images/integrations/
    - images/theme1/
    - images/theme2/
    - images/theme3/
    - images/theme4/
    - images/theme5/
    - images/theme7/
    - images/theme6/
    - images/theme8/
    - images/theme9/
    - images/theme10/
    - images/theme11/
    - images/theme12/
    - images/theme13/
    - images/theme14/
    - images/LikeButton/image/
    - images/walletApp/
    - images/Tinder/images/
    - assets/defaultTheme/
    - images/shophop/img/
    - assets/shophop_data/
    - assets/integrations/
    - assets/medium/
    - assets/integrations/lang/
    - images/medium/mtopics/
    - images/muvi/icons/
    - images/shophop/img/products/
    - images/muvi/images/
    - images/shophop/img/products/shoes/
    - images/shophop/img/products/dress/
    - images/qibus/
    - images/pricingPlans/
    - images/shophop/img/products/banners/
    - images/shophop/img/products/decor/
    - images/newsBlog/
    - images/medium/
    - images/banking/
    - images/LikeButton/
    - images/mediLab/images/
    - images/orapay/
    - assets/meadium_data/
    - images/defaultTheme/
    - images/mediLab/
    - images/quiz/
    - images/eventApp/
    - images/defaultTheme/banner/
    - images/flag/
    - images/dating/
    - images/dashboard/
    - images/social/
    - images/muvi/
    - images/shophop/
    - images/Reaction/images/
    - images/defaultTheme/category/
    - images/Reaction/
    - images/cloudStorage/
    - images/Tinder/
    - images/smartDeck/
    - images/learner/
    - images/Reaction/images/SocialMedia/
    - images/smartDeck/images/
    - images/hairSalon/
    - images/food/
    - images/mpmusic/
    - images/grocery/
    - assets/pdf/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

