        
name: .NET

on:
  push:
    branches: [ Dev-Deploy ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PublicWorkflow/PublicWorkflow.Api
    - name: Build
      run: dotnet build --no-restore
      working-directory: PublicWorkflow
    #- name: Test
    # run: dotnet test --no-build --verbosity normal
    - name: dotnet Publish
      run: dotnet publish
      working-directory: PublicWorkflow/PublicWorkflow.Api
      #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '**/appsettings.json'
      env:
        ConnectionStrings.ApplicationConnection: ${{ secrets.DEFAULT }}
        ConnectionStrings.IdentityConnection: ${{ secrets.IDENTITY }}
        ConnectionStrings.HangfireConnection: ${{ secrets.HANGFIRE }}
        # MailSettings.Password: ${{ secrets.MAILPASSWORD }}
        # otpSettings.EstoreUsername: ${{ secrets.ESTOREUSERNAME }}
        # otpSettings.EstorePassword: ${{ secrets.ESTOREPASSWORD }}
        # otpSettings.nigeriabulksmsUsername: ${{ secrets.BULKUSERNAME }}
        # otpSettings.nigeriabulksmsPassword: ${{ secrets.BULKPASSWORD }}
        # otpSettings.Caller: ${{ secrets.CALLER }}
        # Sentry.Dsn: ${{ secrets.SENTRYDNS }}
    # - uses: actions/upload-artifact@v2
      # with:
        # name: my-artifact
        # path: PropExpert/PropExpert.Api/bin/Debug/net5.0/publish
    - name: Stop Service Http Port
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: kill -9 $(lsof -t -i:5000)
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY}}
      env:
        CI: true
    - name: Stop Service Https Port
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: kill -9 $(lsof -t -i:5001)
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY}}
      env:
        CI: true
    - name: Empty Deployment folder
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: rm -rf ${{ secrets.REMOTE_TARGET }}/*
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY}}
      env:
        CI: true
    - name: Copy files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: 22
        key: ${{ secrets.REMOTE_SSH_KEY }}
        source: "PublicWorkflow/PublicWorkflow.Api/bin/Debug/net5.0/publish/"
        target: ${{ secrets.REMOTE_TARGET }}
        strip_components: 6
    - name: start app
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: ${{ secrets.servicecommand }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY}}
      env:
        CI: true
    # - name: Restart Service
      # uses: garygrossgarten/github-action-ssh@v0.3.0
      # with:
        # command: sudo service propExpert start
        # host: ${{ secrets.REMOTE_HOST }}
        # username: ${{ secrets.REMOTE_USER }}
        # privateKey: ${{ secrets.REMOTE_SSH_KEY}}
      # env:
        # CI: true


