name: Web-Develop

on:
  push:
    branches: [ Web-Develop ]
  pull_request:
    branches: [ Web-Develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    # - name: Run the tests and generate coverage report
      # run: npm test -- --coverage

    - name: Build
      run: yarn build

    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/Generic_Workflow/Generic_Workflow/PublicWorkflow/PublicWorkflow.Api/bin/Debug/net5.0/publish/
        remote: ${{ secrets.REMOTE_TARGET_WEB }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}